version: '3'

services:
  app:
    image: email-generator
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.email-generator.entrypoints=https"
      - "traefik.http.routers.email-generator.rule=Host(`email-generator.local.aydenjahola.com`)"
      - "traefik.http.services.email-generator.loadbalancer.server.port=4000"
    networks:
      - proxy

networks:
  proxy:
    external: true

